event_homepage:
    path:     /hello/{name}
    defaults: { _controller: EventBundle:Default:index }

EventBundle_event:
    resource: "@EventBundle/Resources/config/routing/event.yml"
    prefix:   /