Yoda\EventBundle\Entity\Event:
    type: entity
    table: null
    repositoryClass: Yoda\EventBundle\Entity\EventRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
        time:
            type: datetime
        location:
            type: string
            length: 255
        details:
            type: text
    lifecycleCallbacks: {  }
